version: '3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
    volumes:
      - influxdb-data:/var/lib/influxdb

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    privileged: true
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_TOKEN=your-influxdb-token
      - INFLUXDB_BUCKET=my-bucket
      - INFLUXDB_ORG=my-org

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  influxdb-data: